// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpqjobkdwrbdxnvwnuke.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwcWpvYmtkd3JiZHhudndudWtlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5OTA1NzAsImV4cCI6MjA2NDU2NjU3MH0.zllxkMz3iYum7FT9USRb7qxiFERxI5-2mLHiUkVtnZM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);